name: 余电查询⚡️
on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 20 * * *'

jobs:
  el-query:
    name: 余电查询⚡️
    runs-on: ubuntu-latest
    steps:
      - name: Set timezone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'

      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install node.js modules
        run: 'cd charts; npm install'

      - name: Install python modules
        run: 'pip install -r requirements.txt'

      - run: 'python main.py'
        env:
          CONFIGS: ${{ secrets.CONFIGS }}

      - name: Configure git
        run: 'git config --global user.email "${{ secrets.EMAIL }}"; git config --global user.name "${{ secrets.USERNAME }}"'

      - name: Commit changes
        run: 'git add .; git commit -m "[bot] update chart"; git push origin master'